# Generated by Django 6.0.2 on 2026-02-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='tickets/pdfs/'),
        ),
    ]
